# Generated by Django 5.1 on 2024-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('monthly', 'Monthly Subscription'), ('quarterly', 'Quarterly Subscription'), ('semiannual', 'Semi-Annual Subscription')], max_length=500)),
                ('price', models.BigIntegerField(choices=[(100000, '100,000 Toman'), (270000, '270,000 Toman'), (500000, '500,000 Toman')])),
                ('subscription_type', models.IntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (6, 'Semi-Annual')])),
            ],
        ),
    ]
