# Generated by Django 5.1 on 2024-09-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('title', 'price', 'subscription_type')},
        ),
    ]
