# Generated by Django 5.1 on 2024-09-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_service', '0002_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
