# Generated by Django 5.1 on 2024-09-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_service', '0003_alter_subscription_price_alter_subscription_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
    ]
