# Generated by Django 5.1 on 2024-09-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_service', '0004_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
