# Generated by Django 5.1 on 2024-09-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_service', '0005_subscription_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='phone_number',
        ),
    ]
